[test]
node1 ansible_host=127.0.0.1 ansible_user=node1
node2 ansible_host=127.0.0.1 ansible_user=node2

[prod]
node3 ansible_host=127.0.0.1 ansible_user=node3
node4 ansible_host=127.0.0.1 ansible_user=node4

[extra]
node5 ansible_host=127.0.0.1 ansible_user=node5
